sudo: required
dist: trusty
language: java
jdk:
    - openjdk7
    - oraclejdk8
    - oraclejdk9
    - oraclejdk11
env:
    - WLP_VERSION=18.0.0_04 WLP_LICENSE=L-CTUR-B4WNHE
    - WLP_VERSION=19.0.0_03 WLP_LICENSE=L-CTUR-B9JQES
matrix:
    exclude:
    - jdk: oraclejdk11
      env: WLP_VERSION=18.0.0_04 WLP_LICENSE=L-CTUR-B4WNHE
script:
- travis_wait mvn verify -Ponline-its -Dinvoker.streamLogs=true -DwlpVersion=$WLP_VERSION -DwlpLicense=$WLP_LICENSE -e
