sudo: required
dist: trusty
language: java
jdk:
    - oraclejdk8
    - oraclejdk11
env:
    - WLP_VERSION=20.0.0_09 WLP_LICENSE=L-CTUR-BS3K2V
    - WLP_VERSION=20.0.0_06 WLP_LICENSE=L-CTUR-BPKJTD
script:
    - travis_wait mvn verify -Ponline-its -Dinvoker.streamLogs=true -DwlpVersion=$WLP_VERSION -DwlpLicense=$WLP_LICENSE -e
