# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on:
  push:
    branches: '**'
  pull_request:
    branches: [ main ]

jobs:
  build:

    # Steps represent a sequence of tasks that will be executed as part of the job
    strategy:
      fail-fast: false
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        os: [ubuntu-latest, windows-latest]
        WLP_VERSION: [23.0.0_11]
        java: [21, 17, 11, 8]
        include:
          # match up licenses to WLP versions
          # http://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/index.yml
          - WLP_VERSION: 23.0.0_11
            WLP_LICENSE: L-PVGR-Z33XBN

    runs-on: ${{ matrix.os }}
    name: WL ${{ matrix.WLP_VERSION }}, Java ${{ matrix.java }}, ${{ matrix.os }}
    steps:
    - name: Checkout ci.ant
      uses: actions/checkout@v3
    - name: Setup Java ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - name: Run tests with maven for ubuntu
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: ./mvnw -V verify -Ponline-its -D"invoker.streamLogs"=true -DwlpVersion="${{ matrix.WLP_VERSION }}" -DwlpLicense="${{ matrix.WLP_LICENSE }}" -e
    - name: Run tests with maven for windows
      if: ${{ matrix.os == 'windows-latest' }}
      run: ./mvnw -V verify -Pwindows-online-its -D"invoker.streamLogs"=true -DwlpVersion="${{ matrix.WLP_VERSION }}" -DwlpLicense="${{ matrix.WLP_LICENSE }}" -e
