# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on:
  push:
    branches: '**'
  pull_request:
    branches: [ main ]

jobs:
  build:

    # Steps represent a sequence of tasks that will be executed as part of the job
    strategy:
      fail-fast: false
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        os: [ubuntu-20.04, windows-latest]
        WLP_VERSION: [21.0.0_06, 21.0.0_09]
        java: [11, 8]
        include:
          # match up licenses to WLP versions
          - WLP_VERSION: 21.0.0_06
            WLP_LICENSE: L-CTUR-C2YRUK
          - WLP_VERSION: 21.0.0_09
            WLP_LICENSE: L-CTUR-C5HSM7
        exclude:
          - java: 8
            WLP_VERSION: 21.0.0_06

    runs-on: ${{ matrix.os }}
    name: WL ${{ matrix.WLP_VERSION }}, Java ${{ matrix.java }}, ${{ matrix.os }}
    steps:
    - name: Checkout ci.ant
      uses: actions/checkout@v2
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.2
      with:
        maven-version: 3.8.1
    - name: Setup Java ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - name: Run tests with maven
      run: mvn verify -Ponline-its -D"invoker.streamLogs"=true -DwlpVersion="${{ matrix.WLP_VERSION }}" -DwlpLicense="${{ matrix.WLP_LICENSE }}" -e
